default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: make-format-bugpilot
        name: make format-bugpilot
        entry: make format-bugpilot
        language: system
        pass_filenames: false
      - id: make-check-bugpilot
        name: make check-bugpilot
        entry: make check-bugpilot
        language: system
        pass_filenames: false
